### ISSUE TITLE
kotlin.test support

### ISSUE THREAD

**Issue by codymikol** [codymikol/neotest-kotlin.nvim#15]

**Comment by NickHackman** [comment]
kotlin-test falls under the same exact boat as JUnit here, https://github.com/codymikol/neotest-kotlin/issues/16#issuecomment-3016334788

```kotlin
package org.example

import org.junit.jupiter.api.Assertions.assertEquals
import kotlin.test.Ignore
import kotlin.test.Test

class KotlinTest {
    @Test
    fun pass() {
        assertEquals(1, 1)
    }

    @Test
    fun fail() {
        assertEquals(1, 2)
    }

    @Test
    @Ignore
    fun ignore() {
        assertEquals(1, 5)
    }
}
```

Results in,

```text
KotlinTest > ignore() SKIPPED

KotlinTest > fail() FAILED
    org.opentest4j.AssertionFailedError: expected: <1> but was: <2>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:531)
        at app//org.example.KotlinTest.fail(KotlinTest.kt:15)

KotlinTest > pass() PASSED
```

Same thing, appending `()` to the test name and the same case where the class name is not the fully qualified class name.
