### ISSUE TITLE
junit support

### ISSUE THREAD

**Issue by codymikol** [codymikol/neotest-kotlin.nvim#16]

**Comment by NickHackman** [comment]
It appears JUnit supports most likely falls under the same situation as WordSpec/BehaviorSpec where the testing framework appends text to the name of the test that's hard for us to distinguish via Treesitter from a different type of test (AnnotationSpec in Kotest is the same format as JUnit)

```kotlin
package org.example

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class JUnit5 {
    @Test
    fun pass() {
        assertEquals(1, 1)
    }

    @Test
    fun fail() {
        assertEquals(1, 2)
    }
}
```

This results in Gradle output of

```text
JUnit5 > fail() FAILED
    org.opentest4j.AssertionFailedError: expected: <1> but was: <2>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:531)
        at app//org.example.JUnit5.fail(JUnit5.kt:16)

JUnit5 > pass() PASSED
```

Here they're taking the test name and appending on "()".

My rough idea here, is that we can parse the entire file and see if the `@Test` annotation is from JUnit from the import statements from there we can use the feature in Neotest (https://github.com/nvim-neotest/neotest/issues/516) I opened for WordSpec to append on the `()` and that should work (I have no clue on how we ever support `@ParameterizedTest`).

There's another issue here where we need to support a non Fully Qualified Class Name in the Gradle output parser, since JUnit doesn't give the full name here in the output of `org.example.JUnit5`, but that part is rather trivial.

**Comment by NickHackman** [comment]
This wasn't possible via Treesitter, but is implement in v2.0.0 869c25534190c23a683bb54a30d912980370e73b
